In [1]:
import numpy as np

Let $A = USV^\top$ be the SVD of $A$.

Let $B=US$, then $A=BV^\top$

As an example, let $B=\begin{bmatrix}1&1\\0&1\\-1&1\\2&1\end{bmatrix}$, and $V=[v_1, v_2]$

So $A=BV^\top=\begin{bmatrix}1&1\\0&1\\-1&1\\2&1\end{bmatrix}\begin{bmatrix}v_1^\top\\v_2^\top\end{bmatrix}=\begin{bmatrix}v_1^\top+v_2^\top\\v_2^\top\\-v_1^\top +v_2^\top\\2v_1^\top +v_2^\top\end{bmatrix}$

This means **each row of A  $\in\text{span}(v_1,v_2)$**

## This is how SVD can give us best affine space fitting

### Question: Find the best line that fits (1,2,3), (1,-1,0), (2,3,-2), (1,1,1)

In [2]:
# step 1: put these points as rows of a matrix
A = np.array([[1,2,3],
             [1,-1,0],
             [2,3,-2],
             [1,1,1]])

In [10]:
# step 2: shift each point by (x_mean, y_mean, z_mean)
# this is the same as what was done in PCA
Ac = A - np.mean(A, axis=0)
Ac

array([[-0.25,  0.75,  2.5 ],
       [-0.25, -2.25, -0.5 ],
       [ 0.75,  1.75, -2.5 ],
       [-0.25, -0.25,  0.5 ]])

In [11]:
# step 3: take SVD of Ac
U,S,Vt=np.linalg.svd(Ac)
V=Vt.T
V

array([[-0.21493343,  0.0977009 ,  0.97172947],
       [-0.32723498,  0.9302637 , -0.16591175],
       [ 0.92017438,  0.35364386,  0.16797361]])

line is a 1-dim object, so we take the first col of V

all rows of Ac are approximately lying on span(v1) (a line going through origin)

all rows of A are apprxomately lying on span(v1)+(1.25, 1.25, 0.5) 

In [12]:
np.mean(A, axis=0)

array([1.25, 1.25, 0.5 ])