# Build a Simple Neural Network

In [1]:
import numpy as np

## Define some functions

In [17]:
def relu(x):
    # relu function
    return np.maximum(x, 0)

In [18]:
# test relu
relu(np.array([[-2, 3],
              [5, -3]]))

array([[0, 3],
       [5, 0]])

In [15]:
def cost_J(u, y):
    # MSE cost function: 1 / 2 * ||u-y||^2
    return 0.5*(np.sum((u - y)**2))**0.5

In [16]:
# test cost
cost_J(np.array([1,2]), np.array([2,3]))

np.float64(0.7071067811865476)

## training data
The XOR (Exclusive OR) function is a logical operation that returns TRUE if exactly one of the inputs is true, but FALSE if both are true or both are false

In [19]:
# XOR function
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])
y = y.reshape([n, 1])
print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [20]:
n, p = X.shape

In [6]:
# size (number of nodes) of hidden layer
p1 = 5

# initialization
W1 = np.random.randn(p, p1) # shape is p by p1
W2 = np.random.randn(p1, 1)

# forward propargation (usually should be a for loop, iterate over how many hidden layers there are)
u1 = X@W1
h = relu(u1)
u2 = h@W2

# compute cost
J = cost_J(u2, y)

# backward propagation for computing gradient
du2 = u2 - y
dh = du2@W2.T

# gradient descent



In [7]:
W1

array([[ 1.18063066, -0.38582694, -0.72950362,  1.08757395,  1.01589479],
       [ 0.44657806,  0.07658351,  0.90364115, -0.60699856, -1.61162996]])